# Generated by Django 2.0.2 on 2018-02-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
